function renderForca(){const root=document.createElement('div');root.className='forca';let screen='root',game=null,theme=null,feedback='';const themes=Object.keys(window.DATA.forca.themes);
const back=()=>{if(screen==='game'){screen='themes';game=null}else if(screen==='themes'||screen==='classicVersus'){screen='classic'}else if(screen==='classic'){screen='root'}else{navigate('/');return}feedback='';render()};
const start=(t)=>{theme=t;const words=window.DATA.forca.themes[t]||[];game=createForcaGame(words[Math.floor(Math.random()*words.length)]);screen='game';feedback='';render()};
const actionLetter=(letter)=>{const r=guessForcaLetter(game,letter);if(!r.accepted)return;if(sound.isEnabled('click'))sound.click();feedback=r.correct?'Boa! Letra encontrada.':'Essa letra não está na palavra.';render()};
const actionWord=(input)=>{const r=guessForcaWord(game,input);if(!r.accepted){feedback=r.reason==='invalid'?'Digite a palavra completa para tentar.':'';render();return}if(sound.isEnabled('click'))sound.click();feedback=r.correct?'Acertou a palavra!':'Palpite errado: menos uma chance.';render()};
const renderHangman=()=>{const e=game.errors;return `<div class="forca__hangman" aria-label="Boneco da forca: ${e} de 6 erros"><svg viewBox="0 0 220 250" role="img" aria-hidden="true"><path class="forca__gallows" d="M30 228H190M55 228V24H165M55 24H185M165 24V48"/>${e>=1?'<path class="forca__rope" d="M165 48V66"/>':''}${e>=1?'<circle class="forca__piece" cx="165" cy="84" r="18"/>':''}${e>=2?'<path class="forca__piece" d="M165 102V155"/>':''}${e>=3?'<path class="forca__piece" d="M165 112L140 138"/>':''}${e>=4?'<path class="forca__piece" d="M165 112L190 138"/>':''}${e>=5?'<path class="forca__piece" d="M165 155L142 198"/>':''}${e>=6?'<path class="forca__piece" d="M165 155L188 198"/>':''}</svg><span class="forca__errors">${e}/6 erros</span></div>`};
const renderGame=()=>{const p=getForcaProgress(game),k=getForcaKeyboardState(game),el=document.createElement('section');el.className='forca__game';
el.innerHTML=`<div class="forca__game-top"><span class="forca__theme">Tema · ${theme}</span><span class="forca__chances"><strong>${game.chances}</strong> ${game.chances===1?'chance':'chances'}</span></div><div class="forca__chance-bar"><span style="width:${(game.chances/FORCA_MAX_CHANCES)*100}%"></span></div><div class="forca__play-area">${renderHangman()}<div class="forca__play-side"><div class="forca__word" aria-label="Palavra"><span class="forca__word-length">${game.word.length} letras</span>${p.map(x=>`<span class="forca__letter ${x?'is-revealed':''}">${x||'&nbsp;'}</span>`).join('')}</div><p class="forca__hint">${feedback||'Acertar uma letra não gasta chance. Errar, sim.'}</p><div class="forca__keyboard" aria-label="Letras"></div><div class="forca__game-actions"></div></div></div>`;<div class="forca__keyboard" aria-label="Letras"></div><div class="forca__game-actions"></div>`;
const kb=el.querySelector('.forca__keyboard');'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').forEach(x=>{const b=document.createElement('button');b.type='button';b.className='forca__key';b.textContent=x;const l=x.toLowerCase();if(k[l]||game.status!=='playing'){b.disabled=true;if(k[l])b.classList.add('is-'+k[l])}b.onclick=()=>actionLetter(l);kb.append(b)});
const a=el.querySelector('.forca__game-actions');if(game.status==='playing'){const row=document.createElement('div');row.className='forca__word-action';const i=document.createElement('input');i.className='forca__word-input';i.maxLength=game.word.length;i.autocomplete='off';i.autocapitalize='none';i.spellcheck=false;i.placeholder='Digite a palavra';const b=document.createElement('button');b.type='button';b.className='forca__word-button';b.textContent='🎯 Chutar palavra';b.onclick=()=>actionWord(i.value);i.onkeydown=e=>{if(e.key==='Enter')actionWord(i.value)};row.append(i,b);a.append(row);requestAnimationFrame(()=>i.focus())}else{const result=document.createElement('div');result.className=`forca__result is-${game.status}`;result.innerHTML=game.status==='won'?'<strong>Você acertou!</strong><span>Palavra descoberta.</span>':`<strong>Fim de jogo.</strong><span>A palavra era <b>${game.word.toUpperCase()}</b>.</span>`;const b=document.createElement('button');b.type='button';b.className='forca__word-button';b.textContent='↻ Jogar de novo';b.onclick=()=>start(theme);a.append(result,b)}return el};
const bindKeyboard=()=>{root.onkeydown=e=>{if(screen!=='game'||!game||game.status!=='playing'||e.ctrlKey||e.metaKey||e.altKey)return;const target=e.target;if(target&&(['INPUT','TEXTAREA','SELECT'].includes(target.tagName)||target.isContentEditable))return;if(/^[a-zA-Z]$/.test(e.key)){const l=e.key.toLowerCase();if(!game.usedLetters.includes(l)){e.preventDefault();actionLetter(l)}}}};
const render=()=>{root.innerHTML='';root.classList.toggle('forca--playing',screen==='game');if(screen==='game'){root.append(renderGame());return}const h=document.createElement('header');h.className='forca__header';h.innerHTML='<span class="forca__eyebrow">Cúmplices</span><h1 class="forca__title">Forca</h1>';const s=document.createElement('div');s.className='forca__screen';let opts=screen==='root'?[['classic','🔤','Clássico','O jogo de Forca tradicional.'],['termo','🔠','Termo','Palavra do Dia, Aleatório e Versus.']]:screen==='classic'?[['coop','🤝','Coop','Todos juntos contra o aplicativo.'],['versus','⚔️','Versus','Times ou Todos contra todos.']]:screen==='themes'?themes.map(t=>[t,'🎴',t,'Sortear uma palavra deste tema.']):[['teams','👥','Times','Um time escolhe a palavra.'],['free','🧑‍🤝‍🧑','Todos contra todos','Um Mestre e os demais jogadores.']];const o=document.createElement('div');o.className='forca__options';opts.forEach(([id,ic,t,d])=>{const b=document.createElement('button');b.type='button';b.className='forca__option';b.innerHTML=`<span class="forca__option-icon">${ic}</span><span class="forca__option-copy"><strong>${t}</strong><small>${d}</small></span>`;b.onclick=()=>{if(screen==='root'&&id==='classic')screen='classic';else if(screen==='root'&&id==='termo')navigate('/termo');else if(screen==='classic'&&id==='coop')screen='themes';else if(screen==='classic'&&id==='versus')screen='classicVersus';else if(screen==='themes')start(id);else return;render()};o.append(b)});s.append(o);const b=document.createElement('button');b.type='button';b.className='forca__back';b.textContent='← Voltar';b.onclick=back;s.append(b);root.append(h,s)};
root.tabIndex=0;bindKeyboard();root.cleanup=()=>{root.onkeydown=null};render();return root}